{% set name = "minizip" %}
{% set version = "4.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zlib-ng/minizip-ng/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: c362e35ee973fa7be58cc5e38a4a6c23cc8f7e652555daf4f115a9eb2d3a6be7
  patches:
    - win_patch_output_name.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('minizip', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}  # [not win]
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - bzip2
    - libiconv  # [not win]
    - openssl  # [not win]
    - liblzma-devel
    - zlib
    - zstd

test:
  commands:
    # presence of shared libraries
    - test -f $PREFIX/lib/libminizip${SHLIB_EXT}        # [unix]
    - if not exist %LIBRARY_BIN%\libminizip.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\libminizip.lib exit 1  # [win]

    # absence of static libraries
    - test ! -f $PREFIX/lib/libminizip.a                # [unix]

about:
  home: https://github.com/zlib-ng/minizip-ng
  # http://zlib.net/zlib_license.html
  license: Zlib
  license_family: Other
  license_file: LICENSE
  summary: minizip-ng is a zip manipulation library written in C.
  description: |
    minizip-ng is a zip manipulation library written in C
  dev_url: https://github.com/zlib-ng/minizip-ng

extra:
  recipe-maintainers:
    - akrherz
