{% set version = "1.2" %}

package:
  name: minizip-split
  version: {{ version }}

source:
  # upstream does not have tags before 2.0, just a branch
  # https://github.com/zlib-ng/minizip-ng/tree/1.2;
  # for reproducibility, we point to a specific commit
  git_url: https://github.com/zlib-ng/minizip-ng.git
  git_rev: 8658af7e0a73d6ac4d94e81dde0e9fa95b1aff47
  patches:
    - patches/0001-set-separate-suffix-for-static-builds-on-windows.patch

build:
  number: 1

outputs:
  - name: minizip
    script: build-lib.sh   # [unix]
    script: build-lib.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('minizip', max_pin='x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make   # [unix]
        - ninja  # [win]
        - pkg-config
      host:
        - zlib
    test:
      commands:
        # presence of shared libraries
        - test -f $PREFIX/lib/libminizip${SHLIB_EXT}        # [unix]
        - if not exist %LIBRARY_BIN%\minizip.dll exit 1     # [win]
        - if not exist %LIBRARY_LIB%\minizip.lib exit 1     # [win]

        # absence of static libraries
        - test ! -f $PREFIX/lib/libminizip.a                # [unix]
        - if exist %LIBRARY_LIB%\minizip_static.lib exit 1  # [win]

  - name: minizip-static
    script: build-lib.sh   # [unix]
    script: build-lib.bat  # [win]
    build:
      always_include_files:
        # Must overwrite cmake metadata from minizip
        - lib/cmake/minizip/          # [unix]
        - Library/lib/cmake/minizip/  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make   # [unix]
        - ninja  # [win]
        - pkg-config
      host:
        - {{ pin_subpackage("minizip", exact=True) }}
        - zlib
      run:
        - {{ pin_subpackage("minizip", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/libminizip.a                      # [unix]
        - if not exist %LIBRARY_LIB%\minizip_static.lib exit 1  # [win]

about:
  home: https://github.com/zlib-ng/minizip-ng
  # http://zlib.net/zlib_license.html
  license: Zlib
  license_family: Other
  license_file: LICENSE
  summary: minizip-ng is a zip manipulation library written in C.
  description: |
    minizip-ng is a zip manipulation library written in C
  dev_url: https://github.com/zlib-ng/minizip-ng

extra:
  recipe-maintainers:
    - akrherz
  feedstock-name: minizip
