{% set name = "minizip" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zlib-ng/minizip-ng/archive/refs/heads/{{ version }}.zip
  sha256: 2efb96485712375b2fd0e94bd84cc9d3559dfd3a82c27ac66cf6b25b61278cbf

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('minizip', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [not win]
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libminizip${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\minizip.lib exit 1  # [win]

about:
  home: https://github.com/zlib-ng/minizip-ng
  # http://zlib.net/zlib_license.html
  license: Zlib
  license_family: Other
  license_file: LICENSE
  summary: minizip-ng is a zip manipulation library written in C.
  description: |
    minizip-ng is a zip manipulation library written in C
  dev_url: https://github.com/zlib-ng/minizip-ng

extra:
  recipe-maintainers:
    - akrherz
